# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensor_array.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensor_array.proto',
  package='avatar',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12tensor_array.proto\x12\x06\x61vatar\x1a&tensorflow/core/framework/tensor.proto\"<\n\x10TensorArrayProto\x12(\n\x07tensors\x18\x01 \x03(\x0b\x32\x17.tensorflow.TensorProtob\x06proto3')
  ,
  dependencies=[tensorflow_dot_core_dot_framework_dot_tensor__pb2.DESCRIPTOR,])




_TENSORARRAYPROTO = _descriptor.Descriptor(
  name='TensorArrayProto',
  full_name='avatar.TensorArrayProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensors', full_name='avatar.TensorArrayProto.tensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=130,
)

_TENSORARRAYPROTO.fields_by_name['tensors'].message_type = tensorflow_dot_core_dot_framework_dot_tensor__pb2._TENSORPROTO
DESCRIPTOR.message_types_by_name['TensorArrayProto'] = _TENSORARRAYPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TensorArrayProto = _reflection.GeneratedProtocolMessageType('TensorArrayProto', (_message.Message,), {
  'DESCRIPTOR' : _TENSORARRAYPROTO,
  '__module__' : 'tensor_array_pb2'
  # @@protoc_insertion_point(class_scope:avatar.TensorArrayProto)
  })
_sym_db.RegisterMessage(TensorArrayProto)


# @@protoc_insertion_point(module_scope)
